# [build]
#   command = "pip install -r requirements.txt && npm install netlify-lambda && netlify-lambda build src"
#   publish = "build"
#   functions = "functions"

[build]
  # publish: フロントエンドのファイルがあるディレクトリ (今回はルート)
  publish = "."
  # functions: Netlify Functions のソースコードがあるディレクトリ
  functions = "netlify/functions"
  # command: ビルド時に実行するコマンド (依存関係のインストール)
  command = "pip install -r netlify/functions/requirements.txt"

# Python Functions の依存関係を自動インストールする設定 (推奨)
[functions]
  included_files = ["netlify/functions/app.py"] # ハンドラー以外に必要なファイルがあれば指定
  # Netlify は functions ディレクトリ内の requirements.txt を自動で検出してインストールを試みます
  # node_bundler = "esbuild" # Node.js関数の場合

# APIリクエストをFunctionにルーティングする設定
[[redirects]]
  # フロントエンドからの /api/ へのリクエストを...
  from = "/api/*"
  # ...対応する Netlify Function に書き換える
  to = "/.netlify/functions/app/:splat" # 関数ファイル名を app.py に合わせる
  # HTTPステータスコード 200 OK (書き換えを示す)
  status = 200
  # force = true # もし同名の静的ファイルがあっても強制的にリダイレクトする場合