# [build]
#   command = "pip install -r requirements.txt && npm install netlify-lambda && netlify-lambda build src"
#   publish = "build"
#   functions = "functions"

[build]
  # publish: フロントエンドのファイルがあるディレクトリ (今回はルート)
  publish = "."
  # functions: Netlify Functions のソースコードがあるディレクトリ
  functions = "netlify/functions"
  # command: ビルド時に実行するコマンド (依存関係のインストール)
  command = "pip install -r netlify/functions/requirements.txt"

# Python Functions の設定 - ディレクトリを明示的に指定
[functions]
  directory = "netlify/functions"
  # included_files は指定しない

# APIリクエストをFunctionにルーティングする設定
[[redirects]]
  # フロントエンドからの /api/ へのリクエストを...
  from = "/api/*"
  # ...対応する Netlify Function に書き換える
  to = "/.netlify/functions/api/:splat" # 関数ファイル名を api.py に合わせる
  # HTTPステータスコード 200 OK (書き換えを示す)
  status = 200
  # force = true # もし同名の静的ファイルがあっても強制的にリダイレクトする場合